export const SORTED_SONGS_RECEIVED = 'SORTED_SONGS_RECEIVED';
export const FILTERED_SONGS_RECEIVED = 'FILTERED_SONGS_RECEIVED';
export const SWITCHED_PAGE = 'SWITCHED_PAGE';
export const SONG_CHANGED = 'SONG_CHANGED';
export const SONGS_RECEIVED = 'SONGS_RECEIVED';
export const REFRESH_PAGES = 'REFRESH_PAGES';
export const CHANGE_FILTERS = 'CHANGE_FILTERS';
