export const SORTED_ACTIVITIES_RECEIVED = 'SORTED_ACTIVITIES_RECEIVED';
export const FILTERED_ACTIVITIES_RECEIVED = 'FILTERED_ACTIVITIES_RECEIVED';
export const ACTIVITY_CHANGED = 'ACTIVITY_CHANGED';
export const MUSIC_RECEIVED = 'MUSIC_RECEIVED';
